### ISSUE TITLE
Accuracy about baseline tent

### ISSUE THREAD

**Issue by TIEHua** [mr-eggplant/EATA#2]
Hi, sorry to bother you, I tried this to run the tent in your code, but found that the precision I got was very low. 
The command I run is：
python3 main.py --data ./imagenet --data_corruption ./imagenet-c --exp_type 'continual' --algorithm 'tent' --arch 'resnet50' --output ./base/resnet50_tent
I got very low accuracy:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/34273440/224509496-d9c5f68f-3dc2-4c70-a829-c719884c9c96.png">
Do I need to modify some parameters？
Thank you for your time. I am looking forward to your reply.

**Comment by mr-eggplant** [comment]
Hi, 

Thanks for your interest!

These results are correct for Tent (Continual), see dashed lines in Figure 3 (right).
Continual adaptation is more challenging. And the model of Tent tends to collapse as the adaptation goes by.

Best,

**Comment by TIEHua** [comment]
> Figure 3 (right).
I see, thank you.
