### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by stes** [mr-eggplant/EATA#4]
Hi all, thanks for the great work and nice codebase!

I wanted to note that right now a LICENSE is missing, with some implications [on how others are allowed to use the code](https://choosealicense.com/no-permission/).

Could you clarify if this is intended, or whether you actually want to open source the work (under MIT, Apache 2, etc?). If that's the case I am also happy to open a PR!

**Comment by mr-eggplant** [comment]
Hi Steffen, Thank you for your kind reminder! We have updated the license. Best,

**Comment by stes** [comment]
Thanks for the fast reply!
