### ISSUE TITLE
Question: Fig 3 accuracy differences?

### ISSUE THREAD

**Issue by justinkay** [mr-eggplant/EATA#8]
Hi there, thanks for the interesting work.

I have a question about Figure 3 of the paper: For the Gaussian noise setting, shouldn't the numbers be the same between the left and right plots (since it is the first episode of the lifelong adaptation scenario)? Why do you instead obtain ~68% corruption accuracy for gaussian noise in the left plot but ~35% in the right plot?

**Comment by mr-eggplant** [comment]
Hi, thanks for your interest! Figure 3 has two y-axes and the "corruption accuracy" corresponds to the right y-axis (in blue color). So, they are the same ~35%

**Comment by justinkay** [comment]
Ah, I see! Thanks for the clarification!
